import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Underconstruction from './underconstruction';
import { ThemeProvider } from '@/components/theme-provider';
import Navbar from '@/components/navbar';
import Container from '@/components/ui/container';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const isUnderConstruction = false;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {isUnderConstruction ? (
            <Underconstruction />
          ) : (
            <>
              <Container>
                <Navbar /> {children}
              </Container>
            </>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
