import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Underconstruction from './underconstruction';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const isUnderConstruction = true;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{isUnderConstruction ? <Underconstruction /> : children}</body>
    </html>
  );
}
